samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31284_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31284_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10444_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10444_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31281_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31281_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31317_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31317_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31728_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31728_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31304_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31304_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10241_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10241_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31727_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31727_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31306_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31306_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31303_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31303_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1031_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1031_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10443_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10443_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10242_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10242_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31311_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31311_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10244_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10244_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31299_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31299_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31307_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31307_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31282_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31282_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1034_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1034_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31298_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31298_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31300_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31300_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31315_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31315_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31292_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31292_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31280_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31280_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31278_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31278_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10442_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10442_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31291_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31291_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1035_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1035_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31305_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31305_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31316_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31316_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10441_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10441_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31310_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31310_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31279_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31279_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31290_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31290_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10243_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10243_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31309_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31309_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1033_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1033_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1036_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1036_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31302_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31302_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31726_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31726_flagstat.txt
samtools flagstat /media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31318_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31318_flagstat.txt
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31284_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31284_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10444_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10444_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31281_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31281_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31317_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31317_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31728_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31728_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31304_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31304_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10241_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10241_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31727_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31727_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31306_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31306_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31303_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31303_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1031_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1031_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10443_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10443_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10242_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10242_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31311_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31311_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10244_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10244_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31299_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31299_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31307_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31307_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31282_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31282_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1034_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1034_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31298_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31298_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31300_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31300_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31315_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31315_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31292_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31292_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31280_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31280_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31278_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31278_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10442_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10442_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31291_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31291_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1035_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1035_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31305_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31305_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31316_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31316_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10441_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10441_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31310_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31310_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31279_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31279_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31290_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31290_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/10243_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10243_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31309_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31309_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1033_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1033_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/1036_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1036_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31302_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31302_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31726_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31726_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
java -jar /software/bin/picard.jar CollectAlignmentSummaryMetrics I=/media/qnapugdg8tb_2b/cmc_projects_tmp/impronta_exoma/analysis/mapping/mapping_mkdup/31318_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31318_AlignmentSummaryMetrics.txt R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE
