samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31726_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31726_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31280_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31280_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31727_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31727_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31305_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31305_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/10242_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10242_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31303_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31303_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/10444_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10444_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/1036_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1036_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/10442_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10442_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31309_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31309_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/1035_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1035_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/1034_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1034_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31318_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31318_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31728_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31728_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/1033_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//1033_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31291_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31291_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31281_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31281_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31302_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31302_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31307_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31307_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31290_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31290_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31310_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31310_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/10244_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10244_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/10441_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10441_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31279_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31279_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31299_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31299_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31311_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31311_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/10243_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//10243_flagstat.txt
samtools flagstat ../impronta_exoma/analysis/mapping/mapping_mkdup/31304_sorted_mkdup.bam --threads 5 > ../impronta_exoma/analysis/mapping_QC//31304_flagstat.txt
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31726_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31726 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31280_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31280 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31727_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31727 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31305_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31305 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/10242_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10242 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31303_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31303 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/10444_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10444 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/1036_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1036 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/10442_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10442 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31309_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31309 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/1035_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1035 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/1034_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1034 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31318_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31318 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31728_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31728 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/1033_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//1033 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31291_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31291 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31281_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31281 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31302_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31302 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31307_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31307 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31290_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31290 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31310_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31310 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/10244_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10244 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/10441_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10441 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31279_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31279 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31299_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31299 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31311_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31311 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/10243_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//10243 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
java -jar /software/bin/picard.jar CollectMultipleMetrics I=../impronta_exoma/analysis/mapping/mapping_mkdup/31304_sorted_mkdup.bam O=../impronta_exoma/analysis/mapping_QC//31304 R=/nfs/qnapugdg8tb3a/nfs_references/human/1kg/hs37d5/hs37d5.fa ASSUME_SORTED=TRUE INCLUDE_UNPAIRED=TRUE PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=QualityScoreDistribution PROGRAM=MeanQualityByCycle PROGRAM=CollectBaseDistributionByCycle PROGRAM=CollectGcBiasMetrics PROGRAM=CollectSequencingArtifactMetrics
