fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31290_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31304_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31726_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31311_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31311_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31281_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31309_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31284_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31305_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31279_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31309_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31300_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31281_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31318_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31292_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31300_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31315_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31728_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31315_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31302_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31282_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31279_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31299_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31291_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31306_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31306_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31284_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31290_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31298_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31280_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31307_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31303_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31303_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31280_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31292_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31310_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31299_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31278_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31726_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31310_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31302_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31317_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31278_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31727_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31316_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31291_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31282_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31318_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31304_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31307_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31727_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31317_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31298_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31305_R2_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31728_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_merged/31316_R1_merged.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_merged/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31300_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31727_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31302_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31290_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31311_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31302_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31318_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31291_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31290_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31292_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31728_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31305_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31304_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31298_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31280_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31311_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31307_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31279_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31307_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31303_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31316_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31284_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31306_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31310_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31317_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31304_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31317_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31726_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31299_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31281_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31310_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31299_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31298_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31306_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31318_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31292_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31309_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31726_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31309_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31305_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31315_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31278_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31282_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31284_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31282_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31280_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31300_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31291_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31278_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31316_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31303_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31315_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31728_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31727_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31279_R1_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
fastqc ../impronta_exoma/analysis/fastq/fastq_trimmed/31281_R2_merged-trimmed.fastq.gz -o ../impronta_exoma/analysis/fastq_QC/fastq_QC_trimmed/ --extract
